#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$SCRIPT_DIR/../v2rayN/v2rayN.Desktop/bin/Debug/net10.0"
SERVICE_USER="${SUDO_USER:-$(id -un)}"
START_NOW=1
UNIT_PATH=/etc/systemd/system/v2rayn-proxy.service

usage() {
  cat <<EOF
Usage: sudo ./service/install.sh --proxy [options]

Install and enable the Xray proxy to start automatically at device boot.
Quit v2rayN and disable its desktop autostart first to avoid port conflicts.

Options:
  --app-dir DIR   Built v2rayN directory containing bin/ and binConfigs/.
                 Default: this checkout's Debug/net10.0 directory.
  --user USER     Run Xray as this user. Default: sudo's invoking user.
  --no-start      Enable startup at boot without starting the service now.
  -h, --help      Show this help.
EOF
}

die() {
  printf '[service] ERROR: %s\n' "$*" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --app-dir|--user)
      [[ $# -ge 2 && -n "$2" ]] || die "$1 requires a value"
      if [[ "$1" == --app-dir ]]; then APP_DIR="$2"; else SERVICE_USER="$2"; fi
      shift 2
      ;;
    --no-start) START_NOW=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

[[ "$(uname -s)" == Linux ]] || die "This script requires Linux with systemd"
command -v systemctl >/dev/null || die "systemctl was not found"
command -v systemd-analyze >/dev/null || die "systemd-analyze was not found"
[[ "$EUID" -eq 0 ]] || die "Run with sudo: sudo ./service/install.sh --proxy"
[[ -d /run/systemd/system ]] || die "systemd must be running on this device"
id "$SERVICE_USER" >/dev/null 2>&1 || die "User does not exist: $SERVICE_USER"
SERVICE_UID="$(id -u "$SERVICE_USER")"
[[ "$SERVICE_UID" != 0 ]] || die "Use --user to select your normal desktop user"
[[ -d "$APP_DIR" ]] || die "App directory not found. Build first: ./setup.sh --build"
APP_DIR="$(cd -- "$APP_DIR" && pwd -P)"
CORE="$APP_DIR/bin/xray/xray"
CONFIG="$APP_DIR/binConfigs/config.json"
ASSETS="$APP_DIR/bin/xray"
WORK_DIR="$APP_DIR/binConfigs"

[[ -x "$CORE" ]] || die "Xray is missing. Run ./setup.sh --build first"
[[ -s "$CONFIG" ]] || die "Select an Xray server in v2rayN and start its proxy once to generate binConfigs/config.json"
for asset in geoip.dat geosite.dat; do
  [[ -r "$ASSETS/$asset" ]] || die "Missing $ASSETS/$asset. Run ./setup.sh --build"
done

# Environment and ExecStart accept quoted words. WorkingDirectory and User
# take a single value and retain literal quotes, so do not quote those fields.
unit_quote() {
  local value="$1"
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || die "Paths must not contain newlines"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//%/%%}"
  printf '"%s"' "$value"
}

exec_quote() {
  local value="$1"
  value="${value//\$/\$\$}"
  unit_quote "$value"
}

TEMP_DIR="$(mktemp -d)"
TEMP_UNIT="$TEMP_DIR/v2rayn-proxy.service"
trap 'rm -rf -- "$TEMP_DIR"' EXIT
cat > "$TEMP_UNIT" <<EOF
# Generated by service/install.sh. Re-run the installer after moving the app.
[Unit]
Description=v2rayN Xray proxy
Wants=network-online.target
After=network-online.target

[Service]
Type=exec
User=$SERVICE_UID
WorkingDirectory=${WORK_DIR//%/%%}
Environment=$(unit_quote "XRAY_LOCATION_ASSET=$ASSETS")
ExecStart=$(exec_quote "$CORE") run -c $(exec_quote "$CONFIG")
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
UMask=0077

[Install]
WantedBy=multi-user.target
EOF

systemd-analyze verify "$TEMP_UNIT" || die "Generated service failed validation; nothing was installed"
install -m 0644 "$TEMP_UNIT" "$UNIT_PATH"
systemctl daemon-reload
systemctl enable v2rayn-proxy.service

if [[ "$START_NOW" -eq 1 ]]; then
  if ! systemctl restart v2rayn-proxy.service; then
    systemctl status v2rayn-proxy.service --no-pager --full >&2 || true
    die "Startup failed. Check logs with: sudo journalctl -u v2rayn-proxy -n 30 --no-pager"
  fi
fi

printf '[service] Installed and enabled v2rayn-proxy.service for device boot.\n'
printf '[service] Status: systemctl status v2rayn-proxy\n'
printf '[service] Logs: sudo journalctl -u v2rayn-proxy -f\n'
